name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step with variables
        run: echo $VAIR
        env:
          VAIR: jatt

      - name: Job with Variable
        run: echo $JOB

      - name: Workflow with variables
        run: echo $WORK

      - name: Secret
        run: echo "Secret is $SEC"
        env:
          API_KEY: ${{ secrets.TOP_SECRET }}

      - name: My version of Secret
        run: echo ${{secrets.TOP_SECRET}}
    env:
      JOB: ki haal chaal aa dosto
env:
  WORK: yo yo yo yo yo
