name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: cd /

      - name: Step 2
        run: pwd

      - name: Step 3
        run: ls

      - name: Step 4
        run: apt update


