name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Step with variables
        run: echo $VAIR
        env:
          VAIR: jatt

      - name: Job with Variable
        run: echo $JOB

      - name: Workflow with variables
        run: echo $WORK

      - name: Step 4
        run: apt update
    env:
      JOB: ki haal chaal aa dosto
env:
  WORK: yo yo yo yo yo
