name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log files
        run: ls

      - name: Install deps
        run: npm install

      - name: LLL
        run: echo ${{secrets.TOP_SECRET}} | base64

      - name: Log
        run: env
